server:
  port: 8081

spring:
  datasource:
    #url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:file:~/social-neetwork
    username: sa
    password:
    driver-class-name: org.h2.Driver
    
  sql:
    init:      platform: h2
      mode: always      data-locations:      - classpath:sql/init.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:    hibernate:      ddl-auto: update
    properties:      hibernate:
        show_sql: true
        
jwt:
  secret: social_neetwork
