CREATE TABLE IF NOT EXISTS USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  social_name VARCHAR(60) NOT NULL
);


CREATE TABLE IF NOT EXISTS POST (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  post VARCHAR(250) NOT NULL,
  user_id INT NOT NULL,
  date DATE NOT NULL,
  FOREIGN KEY(user_id) REFERENCES USER
);

CREATE TABLE IF NOT EXISTS UPVOTE (
  username VARCHAR(50) NOT NULL,
  post_id VARCHAR(50) NOT NULL
);

